language: python
python: '3.6'
install: pip install virtualenv
script: make
after_success: make push
branches:
    except:
        - gh-pages
env:
    global:
        # GH_TOKEN
        - secure: "rtghUiAHSL8wiPqchzLhqjZCZQVo3ctj0lZtGQmOmNXSSBQuqgbTMPSNWLQn/1QzhqUfAscqLU82KU1M7cHLw6X5AtRu932izkjTeO9HQjHiRU6SA3cRlZNght8d4a2ek4aRm95H1T+6jG9w4PtbgvCw+cWjkR0yhhlH+QHULHerTwbcuzniUlP/bCrEuhBaPjNwsCFiR0qoTI7Hk7ZgnPzyVJHYV6dTt+LjGJW9HJ1YhfxSRNCnzFOzduD2v8p5+pm3CNniRLmYwMtUYvXRH7pREfnQigPY/w+j1ruwxqIfHieUkW4THnFc26P7Bo+UdGU7QXcguDmxl93K4ZY46gY8oCgBtHu8hXLT/UmHFArBs2ZBmCONtWqhH736fhD4unksEqdFZrld4XM6M3lJXNdLiph1sG8uCzQec2bqyHxjhcihi4Q64tDYdpQZ959nuENLrFuPjowjUd8aN+sHXnUSKKGtX0XlChLCVvz4lfQTeKFNmhIDnXR78c9Gy1RReTIEilYJDGSS+93G6AxQda/oWFKvwHv3KmRFxeOyXqfn1MxgCXtW3bHKzbz3NsME7WYHJm195XTRUvadpr+aRx22saODVYUOcjlbTNr1U0qZjqyg+9m3BdTJM34ILjQ8tM0RMo1x2BLsNNqWyfWCU22xxFNNAfnqas/aAoP/Xdo="
cache:
    directories:
        - "$HOME/.cache/pip"
        - "$HOME/.cache/pre-commit"
